#!/usr/bin/env python3
"""Generate refs.bib from citation_pool.json.

BibTeX keys are derived from first-author lastname + year + first-significant-
word of title. Entries use the @article or @inproceedings type based on venue.
"""
import json
import re
from pathlib import Path

WS = Path(__file__).parent
pool = json.loads((WS / "citation_pool.json").read_text())


def safe_key(record: dict) -> str:
    authors = record.get("authors") or ["Anonymous"]
    last = authors[0].split()[-1] if authors else "Anonymous"
    year = record.get("year", "0")
    title = record.get("title", "")
    words = re.findall(r"[A-Za-z]+", title)
    stop = {"a", "an", "the", "of", "for", "and", "or", "in", "on", "with", "to", "from"}
    first = next((w for w in words if w.lower() not in stop), "untitled")
    return f"{last.lower()}{year}{first.lower()}"


def latex_escape(s: str) -> str:
    if not s:
        return ""
    return (s.replace("\\", "\\textbackslash{}")
              .replace("&", "\\&")
              .replace("%", "\\%")
              .replace("_", "\\_")
              .replace("#", "\\#")
              .replace("$", "\\$"))


def to_bibtex(record: dict, key: str) -> str:
    authors = " and ".join(record.get("authors") or [])
    title = record.get("title", "")
    year = record.get("year", "")
    venue = record.get("venue", "") or ""
    ext = record.get("externalIds") or {}
    arxiv = ext.get("ArXiv") or ext.get("arXiv") or ""
    doi = ext.get("DOI") or ""

    entry_type = "article"
    if venue and any(c in venue.lower() for c in ["conf", "proc", "neurips", "iclr", "icml", "cvpr", "acl", "emnlp"]):
        entry_type = "inproceedings"

    lines = [f"@{entry_type}{{{key},"]
    lines.append(f"  title = {{{latex_escape(title)}}},")
    lines.append(f"  author = {{{latex_escape(authors)}}},")
    lines.append(f"  year = {{{year}}},")
    if venue:
        lines.append(f"  {'booktitle' if entry_type == 'inproceedings' else 'journal'} = {{{latex_escape(venue)}}},")
    if arxiv:
        lines.append(f"  eprint = {{{arxiv}}},")
        lines.append(f"  archivePrefix = {{arXiv}},")
    if doi:
        lines.append(f"  doi = {{{doi}}},")
    lines.append("}")
    return "\n".join(lines)


entries = []
seen_keys = set()
for rec in pool:
    base = safe_key(rec)
    key = base
    i = 0
    while key in seen_keys:
        i += 1
        key = f"{base}_{i}"
    seen_keys.add(key)
    rec["_bibkey"] = key
    entries.append(to_bibtex(rec, key))

bib_text = "% refs.bib — generated by paper-orchestra workspace build_bib.py\n"
bib_text += f"% {len(entries)} verified entries\n\n"
bib_text += "\n\n".join(entries) + "\n"

(WS / "refs.bib").write_text(bib_text)
(WS / "citation_pool.json").write_text(json.dumps(pool, indent=2))
print(f"Wrote {len(entries)} entries to refs.bib")
for rec in pool:
    print(f"  \\cite{{{rec['_bibkey']}}} -> {rec['clusters']} -> {rec['title'][:60]}")
